name: update-deps

on:
  workflow_dispatch:
  push:
    tags-ignore:
      - "**"
    branches:
      - '**'
  schedule:
    # once a month
    - cron: "0 0 1 * *"

jobs:
  udd:
    runs-on: ubuntu-latest
    env:
      VR_HOOKS: "false"
    steps:
      - uses: actions/checkout@master
      - uses: denoland/setup-deno@v1
      - uses: jurassiscripts/setup-velociraptor@v1
      - run: deno task udd
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: "chore(deps): update deno dependencies"
          title: Update Deno Dependencies
          body: |
            Automated updates by [deno-udd](https://github.com/hayd/deno-udd)
            and [create-pull-request](https://github.com/peter-evans/create-pull-request)
            GitHub action
          branch: update-deno-dependencies
          author: GitHub <noreply@github.com>
          delete-branch: true
